# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelCli < Formula
  desc "OpenTelemetry command-line tool for sending events from shell scripts & similar environments"
  homepage "https://github.com/equinix-labs/otel-cli"
  version "0.4.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/equinix-labs/otel-cli/releases/download/v0.4.5/otel-cli_0.4.5_darwin_arm64.tar.gz"
      sha256 "809cb66161bea682c7f98f43d36fe0be82e88e85c597194b5b81e3676dbf0fde"

      def install
        bin.install "otel-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/equinix-labs/otel-cli/releases/download/v0.4.5/otel-cli_0.4.5_darwin_amd64.tar.gz"
      sha256 "d8d63bfbbfc18f2cd2f95777d40e063bcd34fcb554bcdfb7d3e636cc54c1eaa3"

      def install
        bin.install "otel-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/equinix-labs/otel-cli/releases/download/v0.4.5/otel-cli_0.4.5_linux_amd64.tar.gz"
      sha256 "2f192fadfb2107a92ae617ca93fd7c0b532fa618a5ebc3917e641c6a9fbaeb45"

      def install
        bin.install "otel-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/equinix-labs/otel-cli/releases/download/v0.4.5/otel-cli_0.4.5_linux_arm64.tar.gz"
      sha256 "f8f27f1289850983f86beaf62968ab65e3491207291d0cdb68247826cc21e695"

      def install
        bin.install "otel-cli"
      end
    end
  end
end
