# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelCli < Formula
  desc "OpenTelemetry command-line tool for sending events from shell scripts & similar environments"
  homepage "https://github.com/equinix-labs/otel-cli"
  version "0.0.16"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/equinix-labs/otel-cli/releases/download/v0.0.16/otel-cli-0.0.16-Darwin-x86_64.tar.gz"
      sha256 "642091d09cea8fac5442a5b6477c84f6942e7858340482de6f8228d8083ad64b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/equinix-labs/otel-cli/releases/download/v0.0.16/otel-cli-0.0.16-Darwin-arm64.tar.gz"
      sha256 "9e3cd13c54c2bb073de939a614ab22660d3302ab5be54e176c03c524a522d68a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/equinix-labs/otel-cli/releases/download/v0.0.16/otel-cli-0.0.16-Linux-x86_64.tar.gz"
      sha256 "8a9de56a851dba4c3ce978c83aa673dcfbe78d9680843182df87a1447c4ed985"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/equinix-labs/otel-cli/releases/download/v0.0.16/otel-cli-0.0.16-Linux-arm64.tar.gz"
      sha256 "058a4c769a262e06c09feefcfb1d4b820a2b1b0f050d0ccc7c9db960de16f81a"
    end
  end

  def install
    bin.install "otel-cli"
  end
end
